name: Release

on:
 push:
    tags:
      - 'v*'

jobs:
  build-desktop:
    strategy:
      matrix:
        settings:
          - host: macos-13
            target: x86_64-apple-darwin
            bundles: dmg,app
            os: darwin
            arch: x86_64
          - host: macos-14
            target: aarch64-apple-darwin
            bundles: dmg,app
            os: darwin
            arch: aarch64
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            bundles: msi
            os: windows
            arch: x86_64
          - host: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            bundles: deb
            os: linux
            arch: x86_64
    name: Build ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup pnpm
          uses: pnpm/action-setup@v4
          with:
            version: 9.15.1
            run_install: false
      
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 22
            cache: 'pnpm'

        - name: Install Dependencies
          run: pnpm i --frozen-lockfile
        
        - name: Package App
          run: pnpm run pack
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

        - name: Get Release Description
          id: release_description
          run: |
            echo "Current tag: ${GITHUB_REF#refs/tags/}"
            {
              echo 'description<<EOF'
              awk '/## \[/ {p=0} /## \['${GITHUB_REF#refs/tags/}'\]/ {p=1;next} p' CHANGELOG.md
              echo 'EOF'
            } >> "$GITHUB_OUTPUT"

        - name: Upload Release Assets
          uses: softprops/action-gh-release@v2
          with:
            tag_name: ${{ github.ref_name }}
            body: ${{ steps.release_description.outputs.description }}  # release description
            files: |
              dist/**/*.dmg
              dist/**/*.msi
              dist/**/*.deb
            draft: false
            prerelease: false
            generate_release_notes: true
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}